#!/usr/bin/env python3
"""Build every template in configs/ and refresh the catalog Location file.

    python3 generator/build_all.py                 # build everything
    python3 generator/build_all.py server-config   # build matching configs only

Register catalog-info.yaml ONCE in the portal; it points at every generated
template, so new templates appear on the next catalog refresh with no extra
registration step.
"""
import glob
import os
import subprocess
import sys

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_DIR = os.path.join(REPO_ROOT, "configs")
BUILDER = os.path.join(REPO_ROOT, "generator", "build_template.py")
LOCATION_FILE = os.path.join(REPO_ROOT, "catalog-info.yaml")


def main() -> None:
    pattern = sys.argv[1] if len(sys.argv) > 1 else ""
    configs = sorted(glob.glob(os.path.join(CONFIG_DIR, "*.yaml")))
    configs = [c for c in configs if pattern in os.path.basename(c)]

    if not configs:
        raise SystemExit(f"no configs matched in {CONFIG_DIR}")

    targets, failures = [], []
    for cfg_path in configs:
        name = os.path.basename(cfg_path)
        result = subprocess.run(
            [sys.executable, BUILDER, "--config", cfg_path],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            failures.append(name)
            print(f"✗ {name}\n{result.stderr.strip()}")
            continue
        print(f"✓ {name}: {result.stdout.strip()}")
        cfg = yaml.safe_load(open(cfg_path, encoding="utf-8"))
        targets.append(f"./{cfg['output_file']}")

    if failures:
        raise SystemExit(f"\n{len(failures)} config(s) failed: {', '.join(failures)}")

    # ---- refresh the Location entity ---------------------------------------
    location = {
        "apiVersion": "backstage.io/v1alpha1",
        "kind": "Location",
        "metadata": {
            "name": "self-service-templates",
            "description": "All generated self-service portal templates",
        },
        "spec": {"type": "url", "targets": targets},
    }
    header = (
        "# ── GENERATED by generator/build_all.py — DO NOT EDIT ────────\n"
        "# Register THIS file once in the portal; it points at every\n"
        "# template below, so new templates need no extra registration.\n"
        "# ─────────────────────────────────────────────────────────────\n"
    )
    with open(LOCATION_FILE, "w", encoding="utf-8") as fh:
        fh.write(header + yaml.safe_dump(location, sort_keys=False, width=100))

    print(f"\nbuilt {len(targets)} template(s); catalog-info.yaml lists:")
    for t in targets:
        print(f"  {t}")


if __name__ == "__main__":
    main()
