---
- name: Listen to Events
  hosts: localhost
  sources:
    - name: Listen to the Host and Port
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Just print the data
      condition: event.payload is defined 
      actions:
        - debug:
            msg: "Received event: {{ event.payload }}"
